   trigger:
     branches:
       include:
         - main  # Change to your default branch

   pool:
     vmImage: 'ubuntu-latest'

   variables:
     ARM_CLIENT_ID: $(servicePrincipalId)
     ARM_CLIENT_SECRET: $(servicePrincipalKey)
     ARM_SUBSCRIPTION_ID: $(subscriptionId)
     ARM_TENANT_ID: $(tenantId)

   stages:
     - stage: Terraform
       jobs:
         - job: Terraform
           steps:
             - task: TerraformInstaller@0
               inputs:
                 terraformVersion: 'latest'

             - script: |
                 terraform init
                 terraform plan
               displayName: 'Terraform Init and Plan'

             - script: |
                 terraform apply -auto-approve
               displayName: 'Terraform Apply'
               env:
                 ARM_CLIENT_ID: $(servicePrincipalId)
                 ARM_CLIENT_SECRET: $(servicePrincipalKey)
                 ARM_SUBSCRIPTION_ID: $(subscriptionId)
                 ARM_TENANT_ID: $(tenantId)